language: node_js
node_js:
 - 12.13.1
cache: npm

before_install:
install:
    - npm ci
before_script:  
script:
   - npm test
after_success:
after_failure:
after_script:
before_deploy:
deploy:
after_deploy: